In [4]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder

In [43]:
file = 'cleaned_data.csv'
df = pd.read_csv(file)
df.dropna(inplace=True)

In [44]:
df = pd.get_dummies(df)
df

,Start Month,Course Flight Hours,E2E Course Days,Course Count,Course Short Name_1 Intro,Course Short Name_2 Private,Course Short Name_3 Inst,Course Short Name_4 Com Sgl,Course Short Name_5 Com Mul,Course Short Name_6 CFI,Course Short Name_7 CFI Std,Course Short Name_8 CFII,Course Short Name_9 MEI
0,9.0,67.7,188,7,0,1,0,0,0,0,0,0,0
1,9.0,43.9,91,4,0,1,0,0,0,0,0,0,0
2,9.0,54.0,120,6,0,1,0,0,0,0,0,0,0
3,9.0,55.2,105,4,0,1,0,0,0,0,0,0,0
4,9.0,62.9,156,7,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1229,3.0,13.6,96,2,1,0,0,0,0,0,0,0,0
1230,3.0,15.4,98,3,1,0,0,0,0,0,0,0,0
1231,3.0,20.4,118,2,1,0,0,0,0,0,0,0,0
1232,3.0,8.2,14,6,1,0,0,0,0,0,0,0,0
1233,1.0,14.4,53,1,0,0,0,0,0,0,1,0,0

In [45]:
X = df.drop('Course Flight Hours', axis=1)
y = df['Course Flight Hours']

In [46]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

# Fitting our model with all our features in X
model.fit(X, y)

score = model.score(X, y)
print(f"R2 Score: {score}")
# YOUR CODE HERE

R2 Score: 0.9362763862935184

In [47]:
print('Weight coefficients: ', model.coef_)
print('y-axis intercept: ', model.intercept_)

Weight coefficients:  [ -0.08091497   0.08319618  -0.8285073  -20.26083611  24.62847608
   6.04227531  80.1607344  -15.75548101 -14.70742176 -23.67915805
 -20.66203868 -15.76655017]
y-axis intercept:  34.57918297780578

In [49]:
x_min = np.array([[X.min()]])
x_max = np.array([[X.max()]])
print(f"Min X Value: {x_min}")
print(f"Max X Value: {x_max}")

Min X Value: [[[1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
Max X Value: [[[ 12. 630.   7.   1.   1.   1.   1.   1.   1.   1.   1.   1.]]]

In [52]:
predictions = model.predict(X)
pd.DataFrame({"Predicted": predictions, "Actual": y, "Error": predictions - y})[["Predicted", "Actual", "Error"]]

x_min = X.min()
x_max = X.max()

y_min_actual = y.min()
y_max_actual = y.max()

y_min_predicted = model.predict([[x_min]])
y_max_predicted = model.predict([[x_max]])
print(f"Actual Min Value: {y_min_actual}")
print(f"Predicted Min Value: {y_min_predicted}")
print(f"Actual Max Value: {y_max_actual}")
print(f"Predicted Max Value: {y_max_predicted}")

ValueError: Found array with dim 3. Estimator expected <= 2.

In [ ]:
nsamples, nx, ny = train_dataset.shape
d2_train_dataset = train_dataset.reshape((nsamples,nx*ny))